version: '3'
services:
    dwtk:
        build: .
        image: hdwlab/dataware-toolkit:master
        container_name: dataware-toolkit
        ports:
            - 8888:8888
        volumes:
            - .:/opt/dataware-toolkit:rw
        working_dir: /opt/dataware-toolkit
        command: >
            bash -c "jupyter nbextension enable --py --sys-prefix widgetsnbextension \
                     && jupyter notebook --allow-root --ip 0.0.0.0 --port 8888"
        tty: true
