version: '3'
services:
    pydtk:
        build: .
        image: hdwlab/pydtk:latest
        container_name: pydtk
        ports:
            - 8888:8888
        volumes:
            - .:/opt/pydtk:rw
        working_dir: /opt/pydtk
        command: >
            bash -c "jupyter nbextension enable --py --sys-prefix widgetsnbextension \
                     && jupyter notebook --allow-root --ip 0.0.0.0 --port 8888"
        tty: true
