version: '3'
volumes:
    venv:

services:
    pydtk:
        image: hdwlab/pydtk:ubuntu-20.04-ros-dev
        container_name: pydtk
        ports:
            - 8888:8888
        volumes:
            - .:/opt/pydtk:rw
            - venv:/opt/pydtk/.venv
        working_dir: /opt/pydtk
        command: >
            bash -c "jupyter nbextension enable --py --sys-prefix widgetsnbextension \
                     && jupyter notebook --allow-root --ip 0.0.0.0 --port 8888"
        tty: true
