name: Document

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy-document:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Build
        run: |
          docker run --rm \
            --volume=${PWD}/doc:/opt/pydtk/doc:rw \
            --volume=${PWD}/pydtk:/opt/pydtk/pydtk:ro \
            --volume=${PWD}/examples:/opt/pydtk/examples:ro \
            --workdir=/opt/pydtk \
            hdwlab/pydtk:0.0.0-ubuntu-20.04-dev \
            /bin/bash -c "pip install nbsphinx sphinx-rtd-theme && cd doc && make html"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/build/html
