name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: 0 0 * * 1

jobs:
  linter-and-test:
    runs-on: ubuntu-20.04
    timeout-minutes: 300
    strategy:
      matrix:
        image_target: ["ubuntu-20.04", "ubuntu-20.04-ros", "ubuntu-22.04-ros2"]

    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Linter and Pytest
        env:
          IMAGE_TARGET: ${{ matrix.image_target }}
        run: make test.${IMAGE_TARGET}

  linter-and-test-ros:
    runs-on: ubuntu-20.04
    timeout-minutes: 300
    strategy:
      matrix:
        image_target: ["ubuntu-20.04-ros"]

    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Linter and Pytest
        env:
          IMAGE_TARGET: ${{ matrix.image_target }}
        run: make test.ros.${IMAGE_TARGET}

  linter-and-test-ros2:
    runs-on: ubuntu-20.04
    timeout-minutes: 300
    strategy:
      matrix:
        image_target: ["ubuntu-22.04-ros2"]

    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Linter and Pytest
        env:
          IMAGE_TARGET: ${{ matrix.image_target }}
        run: make test.ros2.${IMAGE_TARGET}
