name: CI

on: [push, pull_request]

jobs:
  check-skip:
    runs-on: ubuntu-18.04
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"
  linter-and-test:
    runs-on: ubuntu-18.04
    timeout-minutes: 300
    strategy:
      matrix:
        image_target: [
            "ubuntu-20.04",
            "ubuntu-20.04-ros",
            "ubuntu-20.04-ros2"
        ]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Linter and Pytest
        env:
          IMAGE_TARGET: ${{ matrix.image_target }}
        run: make test.${IMAGE_TARGET}

  linter-and-test-ros:
    runs-on: ubuntu-18.04
    timeout-minutes: 300
    strategy:
      matrix:
        image_target: [
            "ubuntu-20.04-ros"
        ]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Linter and Pytest
        env:
          IMAGE_TARGET: ${{ matrix.image_target }}
        run: make test.ros.${IMAGE_TARGET}
