name: Publish to PyPI
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        # python-version: [3.6, 3.7, 3.8, 3.9]
        python-version: [3.7]
        poetry-version: [1.1.15]
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Configure
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: poetry config pypi-token.pypi $PYPI_TOKEN
      - name: Fix version
        env:
          REF: ${{ github.ref }}
        run: |
          export VERSION=$(echo ${REF##*/} | sed 's/[^0-9.]*//g')
          make fix-version
      - name: Build
        run: poetry build
      - name: Publish
        run: poetry publish
