name: CI
on:
  push:
    branches:
      - feature/ci-release-pypi-0.0.0

#on:
#  push:
#    tags:
#      - 'v*.*.*'

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
#        python-version: [3.6, 3.7, 3.8, 3.9]
        python-version: [3.7]
        poetry-version: [1.1.2]
#        os: [ubuntu-18.04, macos-latest, windows-latest]
        os: [ubuntu-18.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Fix version
        shell: bash
        env:
          REF: ${{ github.ref }}
        run: |
          VERSION=$(echo ${REF##*/} | sed 's/[^0-9.]//g')
          sed -i -e 's/0.0.0/'"$VERSION"'/' pyproject.toml
      - name: Configure
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: poetry config pypi-token.pypi $PYPI_TOKEN
      - name: Build
        run: poetry build
      - name: Publish
        run: poetry publish
